package OrmMapping;
// Generated Feb 5, 2017 3:24:05 PM by Hibernate Tools 4.3.1



/**
 * CandidatesEntretienId generated by hbm2java
 */
public class CandidatesEntretienId  implements java.io.Serializable {


     private int candidatesid;
     private int entretienid;

    public CandidatesEntretienId() {
    }

    public CandidatesEntretienId(int candidatesid, int entretienid) {
       this.candidatesid = candidatesid;
       this.entretienid = entretienid;
    }
   
    public int getCandidatesid() {
        return this.candidatesid;
    }
    
    public void setCandidatesid(int candidatesid) {
        this.candidatesid = candidatesid;
    }
    public int getEntretienid() {
        return this.entretienid;
    }
    
    public void setEntretienid(int entretienid) {
        this.entretienid = entretienid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CandidatesEntretienId) ) return false;
		 CandidatesEntretienId castOther = ( CandidatesEntretienId ) other; 
         
		 return (this.getCandidatesid()==castOther.getCandidatesid())
 && (this.getEntretienid()==castOther.getEntretienid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCandidatesid();
         result = 37 * result + this.getEntretienid();
         return result;
   }   


}


