package OrmMapping;
// Generated Feb 5, 2017 3:24:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Candidates generated by hbm2java
 */
public class Candidates  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int age;
     private String ville;
     private String email;
     private String linkedinUrl;
     private Set jobses = new HashSet(0);
     private Set candidatesEntretiens = new HashSet(0);
     private Set jobses_1 = new HashSet(0);

    public Candidates() {
    }

	
    public Candidates(String name, int age, String ville, String email) {
        this.name = name;
        this.age = age;
        this.ville = ville;
        this.email = email;
    }
    public Candidates(String name, int age, String ville, String email, String linkedinUrl, Set jobses, Set candidatesEntretiens, Set jobses_1) {
       this.name = name;
       this.age = age;
       this.ville = ville;
       this.email = email;
       this.linkedinUrl = linkedinUrl;
       this.jobses = jobses;
       this.candidatesEntretiens = candidatesEntretiens;
       this.jobses_1 = jobses_1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLinkedinUrl() {
        return this.linkedinUrl;
    }
    
    public void setLinkedinUrl(String linkedinUrl) {
        this.linkedinUrl = linkedinUrl;
    }
    public Set getJobses() {
        return this.jobses;
    }
    
    public void setJobses(Set jobses) {
        this.jobses = jobses;
    }
    public Set getCandidatesEntretiens() {
        return this.candidatesEntretiens;
    }
    
    public void setCandidatesEntretiens(Set candidatesEntretiens) {
        this.candidatesEntretiens = candidatesEntretiens;
    }
    public Set getJobses_1() {
        return this.jobses_1;
    }
    
    public void setJobses_1(Set jobses_1) {
        this.jobses_1 = jobses_1;
    }




}


