package OrmMapping;
// Generated Feb 5, 2017 3:24:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Entretien generated by hbm2java
 */
public class Entretien  implements java.io.Serializable {


     private Integer id;
     private Jobs jobs;
     private int phaseMax;
     private Set candidatesEntretiens = new HashSet(0);

    public Entretien() {
    }

	
    public Entretien(Jobs jobs, int phaseMax) {
        this.jobs = jobs;
        this.phaseMax = phaseMax;
    }
    public Entretien(Jobs jobs, int phaseMax, Set candidatesEntretiens) {
       this.jobs = jobs;
       this.phaseMax = phaseMax;
       this.candidatesEntretiens = candidatesEntretiens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }
    public int getPhaseMax() {
        return this.phaseMax;
    }
    
    public void setPhaseMax(int phaseMax) {
        this.phaseMax = phaseMax;
    }
    public Set getCandidatesEntretiens() {
        return this.candidatesEntretiens;
    }
    
    public void setCandidatesEntretiens(Set candidatesEntretiens) {
        this.candidatesEntretiens = candidatesEntretiens;
    }




}


