package OrmMapping;
// Generated Feb 5, 2017 3:24:05 PM by Hibernate Tools 4.3.1



/**
 * JobDescription generated by hbm2java
 */
public class JobDescription  implements java.io.Serializable {


     private Integer id;
     private Jobs jobs;
     private String text;

    public JobDescription() {
    }

    public JobDescription(Jobs jobs, String text) {
       this.jobs = jobs;
       this.text = text;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


