package OrmMapping;
// Generated Feb 5, 2017 3:24:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
public class Jobs  implements java.io.Serializable {


     private Integer id;
     private Clients clients;
     private String profil;
     private int status;
     private Set candidateses = new HashSet(0);
     private Set candidateses_1 = new HashSet(0);
     private Set entretiens = new HashSet(0);
     private Set jobDescriptions = new HashSet(0);

    public Jobs() {
    }

	
    public Jobs(Clients clients, String profil, int status) {
        this.clients = clients;
        this.profil = profil;
        this.status = status;
    }
    public Jobs(Clients clients, String profil, int status, Set candidateses, Set candidateses_1, Set entretiens, Set jobDescriptions) {
       this.clients = clients;
       this.profil = profil;
       this.status = status;
       this.candidateses = candidateses;
       this.candidateses_1 = candidateses_1;
       this.entretiens = entretiens;
       this.jobDescriptions = jobDescriptions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public String getProfil() {
        return this.profil;
    }
    
    public void setProfil(String profil) {
        this.profil = profil;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getCandidateses() {
        return this.candidateses;
    }
    
    public void setCandidateses(Set candidateses) {
        this.candidateses = candidateses;
    }
    public Set getCandidateses_1() {
        return this.candidateses_1;
    }
    
    public void setCandidateses_1(Set candidateses_1) {
        this.candidateses_1 = candidateses_1;
    }
    public Set getEntretiens() {
        return this.entretiens;
    }
    
    public void setEntretiens(Set entretiens) {
        this.entretiens = entretiens;
    }
    public Set getJobDescriptions() {
        return this.jobDescriptions;
    }
    
    public void setJobDescriptions(Set jobDescriptions) {
        this.jobDescriptions = jobDescriptions;
    }

    @Override
    public String toString() {
        return profil;
    }

    

}


